### ISSUE TITLE
compile error against fmt version 8.0.1 in windows mingw environment

### ISSUE THREAD

**Issue by zhuoqiang** [odygrd/quill#128]
when using conan, there is a compile error against fmt version 8.0.1

- OS: Windows 10
- Toolchain: MingW g++ 10.3.0
- fmt: `8.0.1`
- quill: `1.6.2`

```
In file included from \quill\src\detail\backend\TimestampFormatter.cpp:5:
/quill/include/quill/detail/misc/Os.h:151:6: error: variable or field 'wstring_to_utf8' declared void
  151 | void wstring_to_utf8(fmt::wmemory_buffer const& w_mem_buffer, fmt::memory_buffer& mem_buffer);
      |      ^~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
```

the conan file for reproduce:

```
[requires]
fmt/8.0.1
quill/1.6.2

[generators]
cmake_find_package
cmake_paths
```

there's no error if using fmt `7.1.2` which is quill `1.6.2` depends on

**Comment by odygrd** [comment]
Hello, thanks for reporting. Sorry been busy over the last few months and haven't updated quill.
Quill needs more changes to adapt to fmt 8.0.1 API
I am looking at it and should update it to work with fmt 8.0.1 over the next few days

**Comment by odygrd** [comment]
hello, latest version from master should compile with fmt 8.0.1.
There is no release yet but I will make one soon

**Comment by odygrd** [comment]
this should now be fixed in release `v1.6.3`

**Comment by zhuoqiang** [comment]
cool, thanks for the quick fix. I will try `v1.6.3` when it lands on conan. Any plan for this?
